apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: rebuild
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: ${REBUILD_IMAGE}
            env:
            - name: IC_KEY
              valueFrom:
                secretKeyRef:
                  name: mysecrets
                  key: ic_apitoken
            - name: CLUSTER
              value: ${CLUSTER}
